'use strict'

var translationsInEnglish = {
    // ui
    // settings
    'app_ui_language_en': 'English',
    'app_ui_language_pl': 'Polish',
    'app_ui_theme_light': 'Light',
    'app_ui_theme_dark': 'Dark',
    'app_ui_theme_gold': 'Gold',
    // states
    'ignored': 'Ignored',
    'found': 'Found',
    'valid': 'Valid',
    'invalid': 'Invalid',
    // buttons
    'reset_settings': 'Reset settings',
    'enable_new_features': 'Enable new features',
    'remove_exams': 'Remove exams',
    'load_questions': 'Load your questions',
    'retrieve_questions': 'Retrieve',
    'prev_short': 'Prev',
    'next_short': 'Next',
    'review_exam': 'Review exam',
    'shubmit_exam': 'Submit exam',
    'retry_exam': 'Retry new questions',
    'repeat_exam': 'Repeat same questions',
    'back_to_result_details': 'Back to result details',
    'back_to_result': 'Back to exam result',
    // exams view
    'questions_in_exam': '%d questions in %d mins',
    // challenge view
    'question': 'Question',
    'choose_answer': 'choose_answer',
    'type_answer': 'Type answer here',
    // review view
    'mark_for_review': 'Mark question for review',
    'answered_in_total': 'Answered in total',
    'missing_answers': 'Missing answers',
    'marked_for_review': 'Marked for review',
    // result view
    'exam_result_header': '${name} exam result',
    'result_perfect': 'Perfect',
    'result_great': 'Great',
    'result_not_good': 'Not good',
    'result_poor': 'Poor',
    'result_terrible': 'Terrible',
    'result_score': 'Your score is ${score}.',
    'result_perfect_details': 'Will you repeat this?',
    'result_great_details': 'You would pass exam.',
    'result_not_good_details': 'You can do it better.',
    'result_poor_details': 'You have to do it better.',
    'result_terrible_details': 'Start to learn wise.',
    'exam_result_correct': 'Questions answered correctly.',
    'exam_result_incorrect': 'Questions with incorrect or missing answer.',
    // print view
    // modals
    'image': 'Image',
    'comment': 'Comment',
    'info': 'About question',
    'info_desc': 'If this question looks broken then check how it looks in Excel file',
    'info_eqi': 'Question in Excel',
    'info_eri': 'Row in Excel',
    'close': 'Close',
    // menu sections
    'about_app': 'About',
    'upload_file': 'Upload file',
    'retrieve_file': 'Retrieve from internet',
    'app_label': 'Application',
    'ui_label': 'User interface',
    'challenges_label': 'Challenge mode',
    'print_label': 'Print mode',
    // menu section items
    'version_desc': 'Current version',
    'source_code_desc': 'Source code available on ${Github}',
    'default_settings_desc': 'Use those actions to back with current options to default settings.',
    'upload_desc': 'Use this option to load questions from your computer or mobile. File content must be in special ${format} to be parsed with application.',
    'retrieve_desc': 'Use this option to load prepared questions from LearnWise cloud storage.',
    'retrieve_placeholder': 'type code here',
    // properties
    'new_feature': 'New feature',
    'app_ui_language_label': 'Preferred language.',
    'app_ui_theme_label': 'Preferred theme.',
    'app_ui_annotations_label': 'Display annotations.',
    'app_ui_annotations_hint': 'This option controls annotations in user preferences.',
    'app_ui_introduction_enabled_label': 'Watch introduction.',
    'app_ui_introduction_enabled_hint': 'This option controls animation when application is starting.',
    'app_ui_animation_before_result_label': 'Watch animation before displaying exam result.',
    'app_ui_animation_before_result_hint': 'This option controls animation before exam result presenting.',
    'app_ui_start_challenge_after_load_success_label': 'Start challenge after loading questions.',
    'app_ui_start_challenge_after_load_success_hint': 'This option starts challenge right after exam has been loaded from file. Print mode cannot be used.',
    'app_ui_start_challenge_after_download_success_label': 'Start challenge after downloading questions.',
    'app_ui_start_challenge_after_download_success_hint': 'This option starts challenge right after exam has been downloaded from internet. Print mode cannot be used.',
    'app_ui_start_challenge_after_selecting_label': 'Start challenge after selecting.',
    'app_ui_start_challenge_after_selecting_hint': 'This option starts challenge right after selection from list without additional use Start button on bottom navigation. Print mode cannot be used.',
    'quiz_questions_mark_for_review_label': 'Allow marking questions for review during challenge.',
    'quiz_questions_mark_for_review_hint': 'This option allows to mark question which can be reviewed before submitting exam.',
    'app_ui_display_nav_below_questions_label': 'Display additional navigation below questions during challenge.',
    'app_ui_display_nav_below_questions_hint': 'This option allows to display additional navigation for previous and next question if available.',
    'quiz_answer_instant_feedback_label': 'Instant feedback.',
    'quiz_answer_instant_feedback_hint': 'This option imediately provides feedback about answer correctness if enabled.',
    'quiz_positive_feedback_audio_label': 'Positive feedback with audio.',
    'quiz_positive_feedback_audio_hint': 'This option provides positive feedback audio for answers when instant feedback is enabled.',
    'quiz_negative_feedback_audio_label': 'Negative feedback with audio.',
    'quiz_negative_feedback_audio_hint': 'This option provides negative feedback audio for answers when instant feedback is enabled.',
    'quiz_answers_help_button_label': 'Allow using Help button during challenge.',
    'quiz_answers_help_button_hint': 'This option allow to use Help button placed on bottom navigation.',
    'quiz_answers_print_letters_label': 'Display letters before answers.',
    'quiz_answers_print_letters_hint': 'This option displays additional letters for before answers.',
    'app_ui_display_progress_label': 'Display progress bar during challenge.',
    'app_ui_display_progress_hint': 'This option displays progress bar on top.',
    'app_ui_display_timer_label': 'Display timer during challenge.',
    'app_ui_display_timer_hint': 'This option displays timer defined for exam or right equivalent for all available questions.',
    'quiz_questions_shuffle_label': 'Shuffle questions.',
    'quiz_questions_shuffle_hint': 'This option allows to shuffle questions used in quiz. Quiz refresh required. Works for all questions in exam only.',
    'quiz_answers_shuffle_label': 'Shuffle available answers.',
    'quiz_answers_shuffle_hint': 'This option allows to shuffle answers appearence order. Quiz refresh required.',
    'quiz_questions_use_all_label': 'Use all available questions.',
    'quiz_questions_use_all_hint': 'This option allows to use all available questions regardless limit set for challenge. Using invalid or ignored questions is controlled by other property.',
    'quiz_questions_skip_ignored_label': 'Skip invalid or ignored questions.',
    'quiz_questions_skip_ignored_hint': 'This option allows to skip invalid/ignored questions, so such which have no correct answer or answers at all.',
    'quiz_auto_restoration_label': 'Auto-restoring saved exam.',
    'quiz_auto_restoration_hint': 'This option allows to restore interrupted challenge. You will back automatically to started challenge when open LearnWise again.',
    'print_questions_skip_ignored_label': 'Skip invalid or marked as ignored questions.',
    'print_questions_skip_ignored_hint': 'This option skips questions without correct answer or without available answers.',
    'print_answers_print_incorrect_label': 'Print incorrect (less visible) answers.',
    'print_answers_print_incorrect_hint': 'This option prints incorrect answers, but less visible.',
    // messages
    'msg_options_change_disabled': 'Changing options is disabled, because your browser does not support localStorage.',
    'msg_prop_not_detected': 'Property value not detected locally. Use switch to set correct value or Reset all settings.',
    'msg_options_has_been_reset': 'Current settings has been reset to default values.',
    'msg_options_reset_disabled': 'Current settings cannot be reset to default values, because your browser does not support localStorage.',
    'msg_options_new_features_enabled': 'New features has been enabled.',
    'msg_version_up_to_date': 'Your version is up-to-date.',
    'confirm_seriously': 'Seriously?',
    'msg_exam_cannot_be_submitted': 'Exam cannot be submitted until all questions will be answered.',
    'msg_exam_loaded_parsed': 'Exam file has been loaded and parsed successfully.',
    'msg_exam_empty_code': 'Empty code.',
    'msg_exam_invalid_code': 'Invalid code.',
    'msg_exam_downloaded_parsed': 'Exam file has been downloaded and parsed successfully.',
    'msg_new_version': 'Application available online has new features. Your local version is outdated. Reset all settings using button placed below.',
    'msg_no_exams': 'You need to load first challenge exam. Use application menu at bottom.',
    'msg_exam_invalid': 'Challenge cannot be started, because has no valid questions.',
    'msg_answers_limit': 'You have to choose %d answers.',
    'msg_answers_limit_exceed': 'You have chosen too many answers.',
    'msg_match_each': 'You have to match each answer.',
    'msg_match_once': 'You cannot use single answer many times.',
    'msg_exams_removed': 'All exams have been removed.'
};