'use strict'

var translationsInPolish = {
    // ui
    // settings
    'app_ui_language_en': 'Angielski',
    'app_ui_language_pl': 'Polski',
    'app_ui_theme_light': 'Jasny',
    'app_ui_theme_dark': 'Ciemny',
    'app_ui_theme_gold': 'Złoty',
    // states
    'ignored': 'Ignorowane',
    'found': 'Znalezione',
    'valid': 'Poprawne',
    'invalid': 'Niepoprawne',
    // buttons
    'reset_settings': 'Przywróć domyślne ustawienia',
    'enable_new_features': 'Aktywuj nowe funkcje',
    'remove_exams': 'Usuń wyzwania',
    'load_questions': 'Wgraj pytania z markdown',
    'upload_questions': 'Wgraj pytania z Excela',
    'retrieve_questions': 'Pobierz',
    'prev_short': 'Poprzednie',
    'next_short': 'Następne',
    'review_exam': 'Przegląd pytań',
    'submit_exam': 'Wyślij egzamin',
    'retry_exam': 'Spróbuj nowych pytań',
    'repeat_exam': 'Powtórz obecne pytania',
    'back_to_result_details': 'Wróć do szczegółów wyniku',
    'back_to_result': 'Wróć do wyniku egzaminu',
    // exams view
    'questions_in_exam': '%d pytań w %d min',
    'filtering_opt_none': 'Brak filtrowania',
    'filtering_opt_version': 'Filtrowanie pytań według wersji',
    'filtering_opt_area': 'Filtrowanie pytań według tagów',
    'filtering_opt_both': 'Fitrowanie pytań według wersji i tagów',
    'filter_version': 'Wersje',
    'filter_tag': 'Tagi',
    'toggle_filters': 'zaznacz/odznacz wszystkie',
    'select_filters': 'zaznacz wszystkie',
    'unselect_filters': 'odznacz wszystkie',
    'filter_opt_empty': 'puste',
    'version_empty': 'brak',
    'tag_empty': 'brak',
    'icon_sync_title': 'Aktualizuj pytania',
    'icon_download_title': 'Pobierz pytania',
    'icon_delete_title': 'Usuń wszystkie pytania',
    'exam_compability_title': 'Zgodność pytań',
    'exam_timestamp_title': 'Wygenerowano',
    // challenge view
    'question': 'Pytanie',
    'choose_answer': 'wybierz odpowiedź',
    'type_answer': 'Wpisz odpowiedź tutaj',
    // review view
    'mark_for_review': 'Oznacz pytanie do przeglądu',
    'answered_in_total': 'Udzielone odpowiedzi',
    'missing_answers': 'Pytania bez odpowiedzi',
    'marked_for_review': 'Oznaczone do przeglądu',
    // result view
    'exam_result_header': 'Wynik egzaminu ${nazwa}',
    'result_perfect': 'Idealnie',
    'result_great': 'Świetnie',
    'result_not_good': 'Niedobrze',
    'result_poor': 'Słabo',
    'result_terrible': 'Tragicznie',
    'result_score': 'Twój wynik to ${wynik}.',
    'result_perfect_details': 'Powtórzysz taki wynik?',
    'result_great_details': 'Prawdopodobnie zdasz egzamin.',
    'result_not_good_details': 'Możesz jeszcze lepiej.',
    'result_poor_details': 'Musisz znacznie lepiej.',
    'result_terrible_details': 'Zacznij uczyć się mądrze.',
    'exam_result_correct': 'Pytania odpowiedziane poprawnie.',
    'exam_result_incorrect': 'Pytanie z błędnymi lub brakującymi odpowiedziami.',
    // print view
    // modals
    'image': 'Obraz',
    'comment': 'Komentarz',
    'info': 'Odnośnie pytania',
    'info_desc': 'Jeśli to pytanie zostało źle wygenrowane to sprawdź jak wygląda w pliku z pytaniami.',
    'info_eqi': 'Pytanie w arkuszu Excela',
    'info_eri': 'Wiersz w arkuszu Excela',
    'close': 'Zamknij',
    // menu sections
    'about_app': 'O aplikacji',
    'upload_file': 'Użyj pliku z pytaniami',
    'retrieve_file': 'Pobierz pytania z internetu',
    'app_label': 'Aplikacja',
    'ui_label': 'Interfejs użytkownika',
    'challenges_label': 'Tryb wyzwania',
    'print_label': 'Tryb drukowania',
    // menu section items
    'version_desc': 'Aktualna wersja',
    'source_code_desc': 'Kod źródłowy dostępny na ${Githubie}',
    'default_settings_desc': 'Użyj tych opcji do przywrócenia ustawień domyślnych.',
    'upload_desc': 'Opcja ta pozwala na wgranie pytań z pamięci komputera lub telefonu. Jednak plik wymaga przygotowania pytań zgodnie z ${formatem} obsługiwanym przez aplikację LearnWise. Druga opcja to wykorzystanie ${szablonu} Excela i dodanie do niego własnych pytań.',
    'retrieve_desc': 'Opcja ta umożliwia pobranie przygotowanych pytań z magazynu aplikacji LearnWise.',
    'retrieve_placeholder': 'tutaj wpisz kod',
    // properties
    'new_feature': 'Nowa funkcja',
    'app_ui_language_label': 'Preferowany język.',
    'app_ui_theme_label': 'Preferowany motyw kolorystyczny.',
    'app_ui_annotations_label': 'Wyświetlaj adnotacje.',
    'app_ui_annotations_hint': 'Opcja wyświetla dodatkowe informacje na temat opcji konfuguracyjnych w menu użytkownika.',
    'app_ui_introduction_enabled_label': 'Zawsze oglądaj intro.',
    'app_ui_introduction_enabled_hint': 'Opcja wyświetla intro podczas uruchamiania aplikacji LearnWise.',
    'app_ui_animation_before_result_label': 'Animacja wyświetlana przed wynikiem zakończonego wyzwania.',
    'app_ui_animation_before_result_hint': 'Opcja kontroluje wyświetlanie animacji przed pokazaniem wyniku egzaminu.',
    'app_ui_start_challenge_after_load_success_label': 'Zacznij wyzwanie po wczytaniu pytań z pliku.',
    'app_ui_start_challenge_after_load_success_hint': 'Opcja umożliwia rozpoczęcie wyzwania bezpośrednio po wczytaniu pytań z pliku. Tryb drukowania będzie wówczas niedostępny.',
    'app_ui_start_challenge_after_download_success_label': 'Zacznij wyzwanie po pobraniu pytań z internetu.',
    'app_ui_start_challenge_after_download_success_hint': 'Opcja umożliwia rozpoczęcie wyzwania bezpośrednio po pobraniu pytań z internetu. Tryb drukowania będzie wówczas niedostępny.',
    'app_ui_start_challenge_after_selecting_label': 'Zacznij wyzwanie po wybraniu.',
    'app_ui_start_challenge_after_selecting_hint': 'Opcja umożliwia rozpoczęcie wyzwania po wbraniu z listy bez konieczności użycia przycisku Start. Tryb drukowania będzie wówczas niedostępny.',
    'quiz_questions_mark_for_review_label': 'Oznaczenie pytania do przeglądu.',
    'quiz_questions_mark_for_review_hint': 'Opcja pozwala na oznaczenie pytania do przeglądu i weryfikacji odpowiedzi przed wysłaniem egzaminu.',
    'quiz_answers_help_button_label': 'Użycie przycisku Pomoc w czasie wyzwania.',
    'quiz_answers_help_button_hint': 'Opcja pozwala na używanie przycisku Pomoc w celu sprawdzenia prawidłowych odpowiedzi.',
    'app_ui_display_nav_below_questions_label': 'Dodatkowe przyciski nawigacyjne poniżej pytania.',
    'app_ui_display_nav_below_questions_hint': 'Opcja wyświetla dodatkowe przyciski nawigacyjne Poprzednie i Następne poniżej pytania.',
    'quiz_answer_instant_feedback_label': 'Natychmiastowa informacja zwrotna.',
    'quiz_answer_instant_feedback_hint': 'Opcja informuje nas o poprawności odpowiedzi, jeśli jest włączona.',
    'quiz_next_question_when_positive_feedback_label': 'Next question after positive feedback.',
    'quiz_next_question_when_positive_feedback_hint': 'This option display next question after positive feedback if possible.',
    'quiz_positive_feedback_audio_label': 'Pozytywna dźwiękowa informacja zwrotna.',
    'quiz_positive_feedback_audio_hint': 'Opcja informuje dźwiękowo o poprawnej odpowiedzi, jeśli natychmiastowa informacja zwrotna jest włączona.',
    'quiz_negative_feedback_audio_label': 'Negatywna dźwiękowa informacja zwrotna.',
    'quiz_negative_feedback_audio_hint': 'Opcja informuje dźwiękowo o błędnej odpowiedzi, jeśli natychmiastowa informacja zwrotna jest włączona',
    'quiz_answers_print_letters_label': 'Litery przed odpowiedziami.',
    'quiz_answers_print_letters_hint': 'Opcja wyświetla dodatkowe litery przed wariantami opowiedzi.',
    'app_ui_display_versions_and_tags_label': 'Wersje i etykiety.',
    'app_ui_display_versions_and_tags_hint': 'Opcja wyświetla wersje i etykiety dla pytań.',
    'app_ui_display_progress_label': 'Pasek postępu.',
    'app_ui_display_progress_hint': 'Opcja wyświetla pasek postępu powyżej pytania.',
    'app_ui_display_timer_label': 'Pomiar czasu.',
    'app_ui_display_timer_hint': 'Opcja wyświetla pomiar czasu w prawym górnym rogu ekranu.',
    'quiz_questions_shuffle_label': 'Losowa kolejność pytań.',
    'quiz_questions_shuffle_hint': 'Opcja zmienia kolejność pytań wyświetlanych podczas wyzwania. Wymaga odświeżenia strony i nowego wyzwania. Działa tylko dla wszystkich pytań.',
    'quiz_answers_shuffle_label': 'Losowa kolejność odpowiedzi.',
    'quiz_answers_shuffle_hint': 'Opcja zmienia kolejność odpowiedzi wyświetlanych podczas wyzwania. Wymaga odświeżenia strony i nowego wyzwania.',
    'quiz_questions_use_all_label': 'Użyj wszystkie dostępne pytania.',
    'quiz_questions_use_all_hint': 'Opcja pozwala na użycie wszystkich dostępnych pytań bez względu na limit pytań danego wyzwania. Użycie nieprawidłowych i ignorowanych pytań kontroluje odrębna opcja.',
    'quiz_questions_skip_ignored_label': 'Pomiń nieprawidłowe pytania.',
    'quiz_questions_skip_ignored_hint': 'Opcja pozwala na pominięcie nieprawidłowych i ignorowanych pytań w wyzwaniu, czyli takich bez prawidłowych odpowiedzi lub zupełnie bez wariantów odpowiedzi.',
    'quiz_auto_restoration_label': 'Automatycznie przywróć wyzwanie.',
    'quiz_auto_restoration_hint': 'Opcja pozwala na przywrócenie przerwanego wyzwania. Automatycznie wrócisz do rozpoczętego wyzwania kiedy ponownie uruchomisz LearnWise.',
    'print_questions_skip_ignored_label': 'Pomiń nieprawidłowe pytania.',
    'print_questions_skip_ignored_hint': 'Opcja pozwala na pominięcie nieprawidłowych i ignorowanych pytań w wyzwaniu, czyli takich bez prawidłowych odpowiedzi lub zupełnie bez wariantów odpowiedzi.',
    'print_answers_print_incorrect_label': 'Wyświetl błędne odpowiedzi',
    'print_answers_print_incorrect_hint': 'Opcja pozwala na wyświetlenie nieprawidłowych odpowiedzi, ale będą mniej widoczne',
    // messages
    'works_since': 'Działa od wersji ${numer}.',
    'msg_not_supported': 'Jeszcze nie działa',
    'msg_options_change_disabled': 'Zmiany ustawień są niedostępne, ponieważ twoja przeglądarka nie obsługuje localStorage.',
    'msg_prop_not_detected': 'Nie wykryto lokalnej wartości opcji konfiguracyjnej. Użyj przełącznika do ustawienia wartości lub Przywróć ustawienia domyślne.',
    'msg_options_has_been_reset': 'Bieżące ustawienia zostały zmienione na domyślne.',
    'msg_options_reset_disabled': 'Bieżące ustawienia niemożliwe do zmiany na domyślne, ponieważ twoja przeglądarka nie obsługuje localStorage.',
    'msg_options_new_features_enabled': 'Nowe funkcje zostały aktywowane. Zmień ich domyślne, wartości jeśli chcesz.',
    'msg_version_up_to_date': 'Twoja wersja jest aktualna.',
    'confirm_seriously': 'Poważnie?',
    'msg_exam_cannot_be_submitted': 'Wysłanie egzaminu niemożliwe dopóki nie odpowiesz na wszystkie pytania.',
    'msg_exam_loaded_parsed': 'Plik egzaminu został wgrany i przetworzony właściwie.',
    'msg_exam_empty_code': 'Brakujący kod.',
    'msg_exam_invalid_code': 'Niepoprawny kod.',
    'msg_exam_downloaded_parsed': 'Plik egzaminu został pobrany i przetworzony właściwie.',
    'msg_new_version': 'Aplikacja posiada nowe funkcje. Twoja lokalna wersja jest przestarzała. Przywróć ustawienia domyślne przyciskiem poniżej.',
    'msg_no_exams': 'Wgraj lub pobierz pierwsze wyzwanie. Użyj menu aplikacji na dole ekranu.',
    'msg_exam_invalid': 'Rozpoczęcie wyzwania jest niemożliwe, ponieważ brakuje poprawnych pytań.',
    'msg_answers_limit': 'Musisz wybrać %d odpowiedzi.',
    'msg_answers_limit_exceed': 'Wybrano zbyt wiele odpowiedzi.',
    'msg_match_each': 'Musisz dopasować każdy z wariantów odpowiedzi.',
    'msg_match_once': 'Nie możesz użyć jednej odpowiedzi wielokrotnie.',
    'msg_exams_removed': 'Wszystkie egzaminy zostały usunięte.',
    'msg_filtering_disabled': 'Filtrowanie pytań według wersji i tagów nie jest jeszcze obsługiwane. Opcje zostały zablokowane.',
    'msg_filtering_info': 'Filtrowanie pytań jest nadal w fazie testów. Dodatkowo wymaga włączenia opcji Użyj wszystkie dostępne pytania.',
    'msg_filtering_warning': 'Filtrowanie pytań jest nadal w fazie testów.',
    'msg_filtering_error': 'Filtrowanie wymaga włączenia opcji **Użyj wszystkie dostępne pytania** oraz odświeżenia aplikacji.'
};